server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/naverpay?serverTimezone=Asia/Seoul
    username: naverpay
    password: externship
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      bindings:
        shortUrlCreated-out-0:
          destination: short_url.created
          content-type: application/json
          producer:
            partition-count: 3

      kafka:
        binder:
          brokers: broker-1:19092, broker-2:19092, broker-3:19092
          auto-create-topics: false
          required-acks: -1
          configuration:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
        bindings:
          shortUrlCreated-out-0:
            producer:
              sync: false
