server:
  port: 8080

security:
  hmac:
    secret: "naverpay-externship"

spring:
  data:
    redis:
      host: localhost
      port: 6380
      repositories:
        enabled: false
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: OrderedRateLimiter
              args:
                key-resolver: "#{@clientIdKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
          routes:
            - id: url-create
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/urls
                - Method=POST
              filters:
                - RewritePath=/api/(?<segment>.*), /${segment}

            - id: url-redirect
              uri: http://localhost:8082
              predicates:
                - Path=/{shortKey}
              filters:
                - name: OrderedRateLimiter
                  args:
                      key-resolver: "#{@clientIdKeyResolver}"
                      redis-rate-limiter.replenishRate: 20
                      redis-rate-limiter.burstCapacity: 40
                      redis-rate-limiter.requestedTokens: 1
                - RewritePath=/(?<key>.*), /v1/urls/${key}

            - id: url-state
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/urls/{shortKey}
                - Method=GET
              filters:
                - RewritePath=/api/(?<segment>.*), /${segment}

            - id: url-statistics
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/urls/{shortKey}/statistics
                - Method=GET
              filters:
                - RewritePath=/api/(?<segment>.*), /${segment}

            - id: top-statistics
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/statistics/top
                - Method=GET
              filters:
                - RewritePath=/api/(?<segment>.*), /${segment}

