CREATE TABLE short_url (
    id INT AUTO_INCREMENT PRIMARY KEY,
    short_key VARCHAR(255) NULL,
    base_url VARCHAR(255) NOT NULL,
    original_url TEXT NOT NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
)